# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f4f91fd14d4f47effd6ecddd7d2ac32d"
application_url = "https://pack-slip.fly.dev"
embedded = true
name = "AquaSlip"

[access_scopes]
scopes = "read_orders,write_orders,read_customers,read_products"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "api/webhooks/order-create"
  topics = [ "orders/create" ]

[auth]
redirect_urls = [ "https://pack-slip.fly.dev/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
